[package]
name = "qgame"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.55"
bevy = { version = "0.6.1", features = ["serialize"] }
bevy_rapier3d = { version = "0.12.1", features = ["enhanced-determinism", "serde-serialize"] }
bytemuck = "1.7.2"
flagset = "0.4.3"
serde = "1.0.136"
toml = "0.5.8"
wgpu = "0.12.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
