[package]
name = "qgame"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = "0.6.1"
bytemuck = "1.7.2"
wgpu = "0.12.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
